//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersDetail
    {
        public string memberId { get; set; }
        public string memberName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public decimal mobileNo { get; set; }
        public string memberType { get; set; }
        public string flatNo { get; set; }
        public string email { get; set; }
        public string societyId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
