//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyDetail
    {
        public string societyId { get; set; }
        public string societyCode { get; set; }
        public string societyName { get; set; }
        public string secretory { get; set; }
        public string address { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
