//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SocietyDBEntities : DbContext
    {
        public SocietyDBEntities()
            : base("name=SocietyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MemberType> MemberTypes { get; set; }
        public DbSet<NumRange> NumRanges { get; set; }
        public DbSet<SocietyDetail> SocietyDetails { get; set; }
        public DbSet<MembersDetail> MembersDetails { get; set; }
    
        public virtual ObjectResult<SP_GetSociety_Result> SP_GetSociety()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSociety_Result>("SP_GetSociety");
        }
    }
}
